const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=require('node:path').resolve(process.argv[2] || '.'),{normalizeCatalogueText,catalogueMatches}=require(root+'/docker/static/site.js');
const rows=[{title:'MRA brain',region:'BRAIN',modality:'MRI',ready:'true'},{title:'CT brain',region:'BRAIN',modality:'CT',ready:'true'},{title:'CT shoulder',region:'UPPER LIMB',modality:'CT arthrogram',ready:'false'},{title:'Ảnh minh họa',region:'BRAIN',modality:'Illustrations',ready:'true'}];
const filters={regions:new Set(),modalities:new Set(),query:'',readyOnly:false};
assert.equal(rows.filter(r=>catalogueMatches(r,filters)).length,4);
filters.modalities.add('MRI');assert.deepEqual(rows.filter(r=>catalogueMatches(r,filters)).map(r=>r.title),['MRA brain']);
filters.modalities.add('CT');assert.equal(rows.filter(r=>catalogueMatches(r,filters)).length,2);
filters.regions.add('UPPER LIMB');assert.equal(rows.filter(r=>catalogueMatches(r,filters)).length,0);
filters.modalities.add('CT arthrogram');assert.equal(rows.filter(r=>catalogueMatches(r,filters)).length,1);
filters.readyOnly=true;assert.equal(rows.filter(r=>catalogueMatches(r,filters)).length,0);
filters.regions.clear();filters.modalities.clear();filters.readyOnly=false;filters.query=normalizeCatalogueText('ANH MINH HOA');assert.equal(rows.filter(r=>catalogueMatches(r,filters))[0].title,'Ảnh minh họa');
const source=fs.readFileSync(root+'/offline_anatomy_viewer/app.js','utf8');
const start=source.indexOf('async function loadCatalogue('),end=source.indexOf('\nfunction filteredModules()',start);
const calls=[],catalogue={modules:[{key:'BRAIN/mri-brain',captured:true},{key:'HEAD AND NECK/ct-face',captured:true}],module_count:2,captured_module_count:2};
const el=new Proxy({},{get:(o,k)=>o[k]??(o[k]={classList:{add(){},remove(){}}})});
const state={catalogueLoading:false,catalogueRequest:0,module:null,capturedOnly:true};
const ctx=vm.createContext({window:{viewerRuntime:{moduleKey:'HEAD AND NECK/ct-face'}},state,el,clearSliceCaches(){},api:async()=>catalogue,renderModuleTree(){},loadPreferences:()=>({moduleKey:'BRAIN/mri-brain'}),selectModule:async(...args)=>calls.push(args)});
vm.runInContext(source.slice(start,end),ctx);
(async()=>{await ctx.loadCatalogue({restore:true});assert.equal(calls[0][0],'HEAD AND NECK/ct-face');assert.equal(calls[0][1].restore,false);ctx.window.viewerRuntime.moduleKey='BRAIN/unknown';await assert.rejects(ctx.loadCatalogue({restore:true}));assert.equal(calls.length,1);ctx.window.viewerRuntime={};await ctx.loadCatalogue({restore:true});assert.equal(calls[1][0],'BRAIN/mri-brain');assert.equal(calls[1][1].restore,true);
const css=fs.readFileSync(root+'/docker/static/site.css','utf8');assert(css.includes('@media(max-width:580px)'));assert(css.includes('@media(max-width:850px)'));assert(css.includes('prefers-reduced-motion'));const js=fs.readFileSync(root+'/docker/static/site.js','utf8');assert(js.includes('dialog.showModal()'));assert(js.includes('event.key === "Escape"'));assert(js.includes('previousFocus?.focus()'));console.log('SITE_FILTERS=PASS; OR_within_AND_across,exact_modalities,ready,accent_search,deep_link,missing_no_fallback,local_restore,responsive_rules,keyboard');})().catch(e=>{console.error(e);process.exit(1)});
